### ISSUE TITLE
Why is this package called gfortran_osx-64?

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/gfortran_osx-64-feedstock#18]
The "osx-64" is already part of the package metadata. It does not need to be part of the package name.

**Comment by beckermr** [comment]
The jinja2 compiler macros rely on compilers being called {language}_{conda subdir}. In a recipe one always writes compiler(‘fortran’) and this gets expanded properly using the various conda build vars. See the conda build documentation for more details.

**Comment by asmeurer** [comment]
Is this package not intended to be installed by end users? If it isn't, that should be made clearer. If it is, there should be a package called just `gfortran`. 

I also don't see why the jinja templates should require the platform to be part of the package. Conda can only install packages that are built for the platform it is running in.

**Comment by asmeurer** [comment]
Also, please don't immediately close issues like this. This issue is not resolved.

**Comment by beckermr** [comment]
My apologies for closing the issue! 

The name cannot be changed as it is required by conda build to have this format. I’d consult the source code for conda build for details if you have interest. 

If you’d like to install the compilers, please see the package named “compilers”.  This is the best way to get the conda compilers for day to day use.

**Comment by isuruf** [comment]
>  Conda can only install packages that are built for the platform it is running in.

There are packages like `clang_osx-64` running on `linux-64` that can cross compile for `osx-64`. That's why the target platform is there in the name. https://anaconda.org/conda-forge/clang_osx-64/files

**Comment by isuruf** [comment]
@asmeurer, PRs are welcome to add a `output` with name `gfortran`.
