### ISSUE TITLE
gfortran compiled executables fail to locate libgfortran.4.dylib

### ISSUE THREAD

**Issue by certik** [conda-forge/gfortran_osx-64-feedstock#3]
When executing such an executable, an error occurs:
```
dyld: Library not loaded: @rpath/libgfortran.4.dylib
  Referenced from /Users/...
  Reason: image not found
```
To fix it, one must execute
```
export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib
```
Then it works.

However, when installing openmpi by hand, the `./configure` script there fails with the same error (even if `DYLD_LIBRARY_PATH` is exported).

It seems this is a bug. The `gfortran` compiler should automatically link the correct path to the gfortran runtime library, so that users do not have to fiddle with `DYLD_LIBRARY_PATH`, and presumably other software, such as openmpi, would also work.

**Comment by beckermr** [comment]
You need to set the rpath linker flags for the conda env

**Comment by beckermr** [comment]
This package is meant for building conda packages not general use as a compiler.

**Comment by certik** [comment]
@beckermr thanks for the feedback. Is there a reason why it can't be used as a general compiler? I installed gfortran using Spack on macOS, and it works both for building packages as well as a general use as a compiler, and it sets the correct path without having to fiddle with `DYLD_LIBRARY_PATH`. I feel there might be a solution so that `gfortran` can be used both for building Conda relocatable packages as well as a general compiler.

**Comment by msarahan** [comment]
Conda does depend a lot on rpath fixing after builds, but if there's a way with spack, there should also be a way we can do it. @katietz @mingwandroid do either of you have suggestions here?

**Comment by certik** [comment]
Well, to be fair, Spack seems to hardwire the full path to gfortran runtime in executables that gfortran creates. But Conda can handle such a thing I thought.

**Comment by isuruf** [comment]
@msarahan, spack uses a compiler wrapper script to automatically add rpath. toolchain3 package was created to do the same thing.

**Comment by beckermr** [comment]
Yup all of this. Also conda forge has its own compiler metapackage as well. At some point we discussed setting the library paths on OS X but then we decided not to. IDK why though...

**Comment by certik** [comment]
Ok, so now I am hitting this issue in a conda-forge package on Linux: https://github.com/conda-forge/dftatom-feedstock/issues/1.

The GCC runtime is linked correctly from $CONDA_PREFIX, but the Fortran runtime is not. This is definitely a bug at this point.

What's the best way to fix this?

**Comment by beckermr** [comment]
I doubt this is an issue with this feedstock, mostly because the version of gfortran you are using was not built here! ;p

I suspect you have a build issue in your cmake invocation.

**Comment by beckermr** [comment]
Turns out the issue above was on linux. I am closing this issue for now.
