### ISSUE TITLE
gfortran_osx-64-7.3.0 causes travis-ci tests to hang

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/gfortran_osx-64-feedstock#8]
Issue:

[One](https://travis-ci.org/cgat-developers/cgat-flow/jobs/598275648) of our travis tests is failing after `gfortran_osx-64-7.3.0` has been upgraded from `4.8.5` to `7.3.0`.

The error we get is:
```
deactivate-gfortran_osx-64.sh made the following environmental changes:

+LDFLAGS=-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs

-DEBUG_FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments

-DEBUG_FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments

-F95=/Users/travis/cgat-install/conda-install/envs/cgat-flow/bin/x86_64-apple-darwin13.4.0-gfortran

-FC=/Users/travis/cgat-install/conda-install/envs/cgat-flow/bin/x86_64-apple-darwin13.4.0-gfortran

-FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe

-FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe

-GFORTRAN=/Users/travis/cgat-install/conda-install/envs/cgat-flow/bin/x86_64-apple-darwin13.4.0-gfortran

/Users/travis/.travis/functions: line 553:  2094 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"

The command "travis_wait 30 ./install-devel.sh --install-repo --test --use-repo ." exited with 1.
```

<br/>
Environment:
<details>

```
# https://github.com/cgat-developers/cgat-core/blob/master/conda/environments/cgat-core.yml

name: cgat-core

channels:
- conda-forge
- bioconda
- defaults

dependencies:
# python dependencies
- python
- gevent
- nose
- numpy
- pandas
- paramiko
- pep8
- pytest
- drmaa
- pyyaml
- ruffus
- setuptools
- six
- sqlalchemy
# Misc dependencies
- coreutils
- nomkl
- time
- boto3
- google-cloud-storage
- google-cloud-sdk
- ftputil
- pysftp

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None

            shell level : 0

       user config file : /Users/travis/.condarc

 populated config files : 

          conda version : 4.7.10

    conda-build version : not installed

         python version : 3.7.3.final.0

       virtual packages : 

       base environment : /Users/travis/cgat-install/conda-install  (writable)

           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/osx-64

                          https://repo.anaconda.com/pkgs/r/noarch

          package cache : /Users/travis/cgat-install/conda-install/pkgs

                          /Users/travis/.conda/pkgs

       envs directories : /Users/travis/cgat-install/conda-install/envs

                          /Users/travis/.conda/envs

               platform : osx-64

             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/17.4.0 OSX/10.13.3

                UID:GID : 501:20

             netrc file : None

           offline mode : False

```
</details>

**Comment by beckermr** [comment]
How did you verify it was this package?

**Comment by sebastian-luna-valero** [comment]
I compared with a [previous](https://travis-ci.org/cgat-developers/cgat-flow/jobs/583233322) successful build where `gfortran_osx-64` is `4.8.5` and we don't get the error.

**Comment by beckermr** [comment]
Got it. What other versions changed from that previous build?

**Comment by sebastian-luna-valero** [comment]
Well, if you look at the build log you can see that we install many conda packages so it will be a big list. However, the travis build hangs after the message:
```
deactivate-gfortran_osx-64.sh made the following environmental changes
```
which made me think that `gfortran` was the culprit, and indeed I noticed that its version changed from `4.8.5` to `7.3.0` from the successful to the failed build.

I am sure you guys have intensively tested the new version but what other thing could be causing the issue?

**Comment by beckermr** [comment]
This new version has been used to migrate over 200 packages and is in use actively by all of conda-forge right now. I am not saying there is not a bug. I am only saying that the chances seem small unless it is a super weird edge case. More information on your side would be very helpful! Right now I don't have enough to go on. 

Those messages are output for debugging purposes and may not indicate what the code is actively doing.

**Comment by sebastian-luna-valero** [comment]
Apologies for the noise. I thought the output above was enough for you to debug. Will keep digging deeper and will report back the results.

**Comment by beckermr** [comment]
No worries! Thank you so much for making the issue! Let me know if you find anything!

**Comment by Acribbs** [comment]
I also have the same problem on this [repo](https://github.com/Acribbs/scflow). 12 days ago [this](https://travis-ci.com/Acribbs/scflow/jobs/241493895) build running gfortran_osx `4.8.5` and 4 days later with no major changes, gfortran_osx running `7.3.0` I get the same [failure ](https://travis-ci.com/Acribbs/scflow/jobs/243121484). Will also look into this further too

**Comment by sebastian-luna-valero** [comment]
Hi,

So the issue in our case happened when we had an active conda environment with `gfortran` installed, and we `conda activate <same-env>` again. It looks like that hangs the bash shell and Travis times out. It only complains on OSX though, not on Linux.

In general, you should not need to activate the same conda environment twice, but I leave the feedback here in case it is useful. Also, I don't have an OSX system at hand to reproduce the issue, but it would be good if any of you could test that.

Sorry again for the noise!

Best regards,
Sebastian
